<?php

/**
 * @file
 * Drupal hooks for supporting tragedy_commons operations.
 */

use Drupal\Component\Render\FormattableMarkup;
use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\markdown\Markdown;

const TRAGEDY_COMMONS_REQUEST = 'Request';
const TRAGEDY_COMMONS_ACCEPTED = 'Accepted';
const TRAGEDY_COMMONS_REJECTED = 'Rejected';

/**
 * Implements hook_help().
 */
function tragedy_commons_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.tragedy_commons') {
    if (\Drupal::moduleHandler()->moduleExists('markdown')) {
      // Use the Markdown filter to render the README.
      // @phpstan-ignore-next-line (Class is optionally included.)
      return Markdown::create()->loadFile(__DIR__ . '/README.md');
    }
    else {
      $text = file_get_contents(__DIR__ . '/README.md');
      return '<pre>' . Html::escape($text) . '</pre>';
    }
  }
  return NULL;
}

/**
 * Implements hook_mail().
 */
function tragedy_commons_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  $config = \Drupal::config('tragedy_commons.settings');

  switch ($key) {
    case 'request':
      $email_string_params = [
        '@firstname' => $params['firstname'],
        '@lastname' => $params['lastname'],
        '@email' => $params['email'],
        '@institution' => $params['institution'],
        '@description' => $params['description'],
        '@request_page' => $params['request_page'],
      ];
      $message['subject'] = t('Tragedy of the Commons Game Request Received', [], $options);
      $body = t('You made the following request to play the Tragedy of the Commons game and it has been received:

First Name: @firstname
Last Name: @lastname
Email: @email
Affiliation: @institution
Purpose: @description

You will receive a response within a week approving or denying this request and providing you with a password to play the game, if approved.

If you have not heard from me within a week, please contact me via email at: rmitchel@uoregon.edu.

Thank you for your interest in the Tragedy of the Commons Game.

Ronald Mitchell
Department of Political Science
University of Oregon
Eugene, OR 97503-1284
Tel: 541-346-4880
Email: rmitchel@uoregon.edu
Web: https://ronaldbmitchell.com/', $email_string_params, $options);
      $message['body'][] = Html::escape($body);
      break;

    case 'request_reviewer':
      $email_string_params = [
        '@firstname' => $params['firstname'],
        '@lastname' => $params['lastname'],
        '@email' => $params['email'],
        '@institution' => $params['institution'],
        '@description' => $params['description'],
        '@request_page' => $params['request_page'],
      ];
      $message['subject'] = t('Approval Sought for Tragedy of the Commons Game', [], $options);
      $body = t('The following request to play the Tragedy of the Commons game has been made:

First Name: @firstname
Last Name: @lastname
Email: @email
Affiliation: @institution
Purpose: @description

To approve or disapprove this request, go to:

@request_page

Ronald Mitchell
Department of Political Science
University of Oregon
Eugene, OR 97503-1284
Tel: 541-346-4880
Email: rmitchel@uoregon.edu
Web: https://ronaldbmitchell.com/', $email_string_params, $options);
      $message['body'][] = Html::escape($body);
      break;

    case 'request_approved':
      $module_base_url = new Url('tragedy_commons.base', [], ['absolute' => TRUE]);
      $test_password = strtolower($params['lastname']) . '-' . $params['test_gid'];
      $password = strtolower($params['lastname']) . '-' . $params['gid'];
      $email_string_params = [
        '@firstname' => $params['firstname'],
        '@lastname' => $params['lastname'],
        '@hbase' => $module_base_url->toString(),
        '@test_password' => $test_password,
        '@test_gid' => $params['test_gid'],
        '@password' => $password,
        '@gid' => $params['gid'],
      ];
      $message['subject'] = t('Tragedy of the Commons Game Request Approved', [], $options);
      $body = t('@firstname @lastname,

Your request to use the multi-person version of the Tragedy of the Commons game has been approved. Before scheduling the game, please learn more about the game and ideas for teaching it at: https://ronaldbmitchell.com/commons/ which has links for the instructions, an example from the multi-person game, my lecture notes and video of my teaching of the course.

I have set up two passwords so your class can play. It is EXTREMELY important that you read and follow the instructions on the webpage above very carefully.

Most importantly, please do a practice run first by getting two or three research assistants or colleagues together. Each of those who will be playing the game to TEST IT should go to:
    @hbase/
and entering the TEST password in the box in the "Enter Password" box. Your test password is:
   @test_password
You will MANAGE the playing of the TEST game at the following page:
   @hbase/gamespace/@test_gid/manage

If that works successfully, then you can play the game with your class by having all your students go to the same page (@hbase/) and have each enter the CLASS password in the "Enter Password" box.  Your class password is:
   @password
You will MANAGE the playing of the CLASS game at the following page:
   @hbase/gamespace/@gid/manage

The practice will make sure you understand the mechanics of how the game works and thereby avoid the embarrassment of it not working properly with the class. It usually works smoothly but it is important that you test it. You can play it anytime - I don\'t need to know when.

Please let me know if the test runs smoothly. If so, then you can schedule the game with your class anytime. The only request I make in exchange for making this game available is that you send me an email after you conclude to let me know how it was received by the students. I have put considerable effort into setting up this game and would like to know how it is used.

Best of luck with the game,
Ron
-----------------
Ronald Mitchell
Department of Political Science
University of Oregon
Eugene, OR 97503-1284
Tel: 541-346-4880
Email: rmitchel@uoregon.edu
Web: https://ronaldbmitchell.com/', $email_string_params, $options);
      $request_approved_email = $config->get('request_approved_email');
      if (!empty($request_approved_email)) {
        $body = new FormattableMarkup($request_approved_email, $email_string_params);
      }
      $message['body'][] = Html::escape($body);
      break;

    case 'request_disapproved':
      $email_string_params = [
        '@reason' => $params['reason'],
      ];
      $message['subject'] = t('Tragedy of the Commons Game Request Denied', [], $options);
      $body = t('@reason

Ronald Mitchell
Department of Political Science
University of Oregon
Eugene, OR 97503-1284
Tel: 541-346-4880
Email: rmitchel@uoregon.edu
Web: https://ronaldbmitchell.com/', $email_string_params, $options);
      $message['body'][] = Html::escape($body);
      break;

    case 'game_played':
      $email_string_params = [
        '@results_page' => $params['results_page'],
      ];
      $message['subject'] = t('Tragedy of the Commons Game just played', [], $options);
      $body = t('Thanks for playing the Tragedy of the Commons Game. The results of your game will be stored permanently at the following web address in case you would like to use them in your teaching: @results_page

The individual game pages that were used in playing the game as well as the management page that you used will be deleted in the next few days, but the pages above should be adequate for you to use in debriefing the game.

I would appreciate you letting me know how the game went, how students responded to the game, and any improvements you can think of for its use in the future.

Sincerely,

Ronald Mitchell
Department of Political Science
University of Oregon
Eugene, OR 97503-1284
Tel: 541-346-4880
Email: rmitchel@uoregon.edu
Web: https://ronaldbmitchell.com/', $email_string_params, $options);
      $message['body'][] = Html::escape($body);
      break;
  }
}
